language: php

branches:
  only:
    - rewrite_unittests

services:
  - mysql

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - PIMCORE_TEST_DRIVER=Mysqli
  - PIMCORE_TEST_DRIVER=Pdo_Mysql

before_script:
  - composer install --dev --prefer-source

script: cd ./tests/ && php ../vendor/bin/phpunit --bootstrap bootstrap.php tests/